### PR TITLE
Close response bodies, update scala, sbt, and sbt plugins

### PR DESCRIPTION
**Pull request by emdash-ie**
## What does this change?

@Divs-B noticed an error [in testing another PR](https://github.com/guardian/editors-picks-uploader/pull/22#issuecomment-2329106575), so I created this PR to fix it. While here, I updated some scala and sbt versions, and updated/removed some plugins to get a passing build locally.

## How to test

- deploy this branch to CODE
- wait for the schedule to trigger the lambda (happens every 5 minutes)
- check the logs and confirm there’s no mention of responses being leaked

### CODE REVIEW

**Comment by emdash-ie** [comment]
Hmmm, I [deployed this to CODE](https://riffraff.gutools.co.uk/deployment/view/6acc3f39-7a72-478c-b741-b034e13135e9), but [the logs](https://logs.gutools.co.uk/s/content-platforms/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(level,message),filters:!(),index:b0be43a0-59d7-11e8-a75a-b7af20e8f748,interval:auto,query:(language:kuery,query:'app.keyword:%20%22editors-picks-uploader-lambda%22%20AND%20stage:%20%22CODE%22'),sort:!(!('@timestamp',desc)))) still show the warning. I guess I haven’t closed the right thing?

**Comment by emdash-ie** [comment]
Ah, I was only closing the response body when the status was a 200! I have now updated it to close in the `else` branch as well: hopefully this should get rid of the warning entirely.

**Comment by emdash-ie** [comment]
[Have deployed a build with closing in the else branch as well](https://riffraff.gutools.co.uk/deployment/view/1c2d16f5-4f95-4434-99ac-4b37208682cd). Should hopefully see the warning gone from the logs the next time it runs.

**Comment by emdash-ie** [comment]
Sure enough, [those warnings have stopped in CODE](https://logs.gutools.co.uk/s/content-platforms/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-24h%2Fh,to:now))&_a=(columns:!(message),filters:!(),index:b0be43a0-59d7-11e8-a75a-b7af20e8f748,interval:auto,query:(language:lucene,query:'app:editors-picks-uploader%20AND%20stage:CODE%20AND%20message:%20leaked'),sort:!(!('@timestamp',desc)))).

**Review by Divs-B — APPROVED** [review]
worth to have these changes in 👍

**Comment by emdash-ie** [comment]
Once this is merged we should be able to enable scala steward on this repository as well – at the moment [it fails](https://github.com/guardian/scala-steward-public-repos/actions/runs/10717123353/job/29716142806), I think because the scala and sbt versions on main are too low.

**Pull request merged**
