### PR TITLE
Fix jackson high vuln and bump facia and aws sdk version

### PR DESCRIPTION
**Pull request by Divs-B**
## What does this change?

This will fix jackson high vulnerability, also bumps facia-json API version from v27 to v30 and aws sdk patch version.

## How to test

Will deploy on CODE and check logs
Snyk test shows no high vulnerability.

## How can we measure success?

No unusual pattern should get detected and vulnerability shouldn't exist anymore.

### CODE REVIEW

**Comment by emdash-ie** [comment]
Ah, I think the problem may actually be that this app isn’t configured in https://github.com/guardian/riffraff-platform – will get that set up now.

**Comment by emdash-ie** [comment]
> Ah, I think the problem may actually be that this app isn’t configured in https://github.com/guardian/riffraff-platform – will get that set up now.

Yup, that’s fixed it! This means we didn’t need to update actions-riff-raff, so we could remove that from this PR if we felt strongly about separating them. (Since this PR is small, I think it’s probably fine to leave it.)

**Comment by Divs-B** [comment]
> > Ah, I think the problem may actually be that this app isn’t configured in https://github.com/guardian/riffraff-platform – will get that set up now.
> 
> Yup, that’s fixed it! This means we didn’t need to update actions-riff-raff, so we could remove that from this PR if we felt strongly about separating them. (Since this PR is small, I think it’s probably fine to leave it.)

Thats great, thanks for sorting this issue @emdash-ie 
lets deploy this to CODE and will check logs.

**Comment by Divs-B** [comment]
logs looking all fine. so good to confirm this PR work.

just will confirm with team, about one of warning appearing in logs in regular basis (not due to this PR) and also exists in PROD. 

image

https://logs.gutools.co.uk/s/content-platforms/goto/9cc683f0-6ac2-11ef-848b-f3a5846d8d80

**Comment by emdash-ie** [comment]
Just pushed to a commit that squashes my last two commits together – meant to do that earlier but forgot!

**Comment by emdash-ie** [comment]
It shouldn’t need retesting, as I was just combining the commits

**Comment by emdash-ie** [comment]
> logs looking all fine. so good to confirm this PR work.
> 
> just will confirm with team, about one of warning appearing in logs in regular basis (not due to this PR) and also exists in PROD.
> image
> 
> https://logs.gutools.co.uk/s/content-platforms/goto/9cc683f0-6ac2-11ef-848b-f3a5846d8d80

Have made https://github.com/guardian/editors-picks-uploader/pull/23 to fix this error :)

**Comment by Divs-B** [comment]
> > logs looking all fine. so good to confirm this PR work.
> > just will confirm with team, about one of warning appearing in logs in regular basis (not due to this PR) and also exists in PROD.
 
> Have made #23 to fix this error :)

Ah thats great! that was quick! 😀  
i can see you have closed the response that was indeed needed. thanks for fixing on that @emdash-ie

**Review by emdash-ie — APPROVED** [review]
Looks good to me! I saw you’ve tested in CODE, plus the updates are sensible and get rid of the snyk warning.

**Pull request merged**
